# Generated by Django 5.2.6 on 2025-09-06 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who acknowledged the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(
                default="system", help_text="Source of the event", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("service_started", "Service Started"),
                    ("service_stopped", "Service Stopped"),
                    ("service_restarted", "Service Restarted"),
                    ("service_created", "Service Created"),
                    ("service_updated", "Service Updated"),
                    ("service_deleted", "Service Deleted"),
                    ("health_check_failed", "Health Check Failed"),
                    ("health_check_recovered", "Health Check Recovered"),
                    ("health_check_success", "Health Check Success"),
                    ("alert_triggered", "Alert Triggered"),
                    ("alert_resolved", "Alert Resolved"),
                    ("alert_created", "Alert Created"),
                    ("alert_updated", "Alert Updated"),
                    ("alert_deleted", "Alert Deleted"),
                    ("system_startup", "System Startup"),
                    ("system_shutdown", "System Shutdown"),
                    ("user_login", "User Login"),
                    ("user_logout", "User Logout"),
                ],
                max_length=50,
            ),
        ),
    ]
