# Generated by Django 5.2.6 on 2025-09-06 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="cooldown_period",
            field=models.IntegerField(
                default=300, help_text="Cooldown period in seconds"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="escalation_delay",
            field=models.IntegerField(
                default=1800, help_text="Escalation delay in seconds"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="escalation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alert",
            name="notification_channels",
            field=models.JSONField(default=list, help_text="Notification channels"),
        ),
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="tags",
            field=models.JSONField(default=list, help_text="Tags for categorization"),
        ),
        migrations.AddField(
            model_name="alert",
            name="trigger_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this alert has been triggered"
            ),
        ),
        migrations.AddField(
            model_name="alerthistory",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alerthistory",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who acknowledged the alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alerthistory",
            name="escalation_level",
            field=models.IntegerField(default=0, help_text="Current escalation level"),
        ),
        migrations.AddField(
            model_name="alerthistory",
            name="notification_channels",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="alerthistory",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alerthistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("triggered", "Triggered"),
                    ("resolved", "Resolved"),
                    ("escalated", "Escalated"),
                    ("acknowledged", "Acknowledged"),
                ],
                default="triggered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("health_check_failure", "Health Check Failure"),
                    ("response_time", "Response Time"),
                    ("service_down", "Service Down"),
                    ("service_up", "Service Up"),
                    ("custom", "Custom"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="condition",
            field=models.JSONField(
                default=dict, help_text="Alert condition configuration"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("triggered", "Triggered"),
                    ("resolved", "Resolved"),
                    ("disabled", "Disabled"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("webhook", "Webhook"),
                            ("sms", "SMS"),
                            ("discord", "Discord"),
                            ("teams", "Microsoft Teams"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Channel configuration"),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
