# Generated by Django 5.2.6 on 2025-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="check_interval",
            field=models.IntegerField(
                default=60, help_text="Health check interval in seconds"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="metadata",
            field=models.JSONField(default=dict, help_text="Additional metadata"),
        ),
        migrations.AddField(
            model_name="service",
            name="retry_count",
            field=models.IntegerField(
                default=3, help_text="Number of retries before marking as unhealthy"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tags",
            field=models.JSONField(default=list, help_text="Tags for categorization"),
        ),
        migrations.AddField(
            model_name="service",
            name="timeout",
            field=models.IntegerField(
                default=30, help_text="Health check timeout in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("unhealthy", "Unhealthy"),
                    ("unknown", "Unknown"),
                    ("starting", "Starting"),
                    ("stopping", "Stopping"),
                    ("restarting", "Restarting"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
