# Generated by Django 5.2.6 on 2025-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthchecks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheck",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Total check duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="error_code",
            field=models.CharField(
                blank=True, help_text="Error code if applicable", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="http_status",
            field=models.IntegerField(
                blank=True, help_text="HTTP status code for HTTP checks", null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcheck",
            name="response_time",
            field=models.FloatField(
                blank=True, help_text="Response time in milliseconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="healthcheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("timeout", "Timeout"),
                    ("error", "Error"),
                    ("skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
    ]
